-- AlterTable
ALTER TABLE `categories` ADD COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ALTER COLUMN `created_at` DROP DEFAULT;

-- AlterTable
ALTER TABLE `tags` ADD COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ALTER COLUMN `created_at` DROP DEFAULT;

-- AlterTable
ALTER TABLE `tasks` ALTER COLUMN `created_at` DROP DEFAULT;

-- AlterTable
ALTER TABLE `user` MODIFY `last_login` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);
